apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common
  - bases/emrcontainers.services.k8s.aws_jobruns.yaml
  - bases/emrcontainers.services.k8s.aws_virtualclusters.yaml
